```{r}
rm(list = ls())

########################################################################
# Source, Library, and Data ############################################
library(tidyverse)
library(Sleuth3)
data(ex1029)

ex1029 <- ex1029 %>% 
  filter(Educ >= 8, Exper <= 40, Exper >= 1) %>% 
  filter(Race == 'NotBlack')
########################################################################
```

```{r}
########################################################################
# Set My Theme for ggplot ##############################################
my_theme <- theme_minimal() +
  theme(
    plot.title = element_text(size = 7),
    axis.title.x = element_text(size = 7),
    axis.text.x = element_text(size = 6),
    axis.title.y = element_text(size = 7),
    axis.text.y = element_text(size = 6),
    legend.title = element_text(size = 7),
    legend.text = element_text(size = 6)
  )
########################################################################
```

```{r}
########################################################################
# Draw Partial Plots with Education ####################################
edu_smoothed_partial_plot <- ex1029 %>% 
  mutate(Exper_bin = cut_width(Exper, width = 5.0, boundary = 7.5)) %>% 
  filter(Exper_bin %in% c("(7.5,12.5]", "(17.5,22.5]", "(27.5,32.5]")) %>%
  ggplot() +
  geom_smooth(method = "loess", 
              aes(x = Educ, y = log(WeeklyEarnings), color = factor(Exper_bin))) + 
  labs(
    title = "A",
    x = "Education (yrs)",
    y = "log(Weekly Earnings) (dollars)",
    color = "Experience (yrs)"
  ) +
  scale_color_viridis_d(labels = c("[8,12]", "[18,22]", "[28,32]")) +
  my_theme + 
  theme(legend.position = "bottom")

edu_smoothed_partial_plot
########################################################################
```


```{r}
########################################################################
# Draw Partial Plots with Experience ###################################
exp_smoothed_partial_plot <- ex1029 %>% 
  filter(Educ %in% c(12, 14, 16, 18)) %>%
  ggplot() +
  geom_smooth(method = "loess", 
              aes(x = Exper, y = log(WeeklyEarnings), color = factor(Educ))) + 
  labs(
    title = "B",
    x = "Experience (yrs)",
    y = "log(Weekly Earnings) (dollars)", 
    color = "Education (yrs)"
  ) +
  scale_color_viridis_d() +
  my_theme + 
  theme(legend.position = "bottom")

exp_smoothed_partial_plot
########################################################################
```


```{r}
########################################################################
# Combine Partial Plots ################################################
smoothed_partial_plots <- ggarrange(
  edu_smoothed_partial_plot, exp_smoothed_partial_plot,
  nrow = 1, ncol = 2, legend = "bottom"
)

smoothed_partial_plots
########################################################################
```

```{r, eval = F}
pdf(
  "../../plots/ex1029/smoothed_partial_plots.pdf",
  width = 5.9, height = 3.4
)
smoothed_partial_plots
dev.off()
```
