```{r}
rm(list = ls())

########################################################################
# Source, Library, and Data ############################################
source("../../axcon/axcon.R")
source("../../axcon/predict_axcon.R")

library(tidyverse)
library(regmdc)
library(Sleuth3)

ex1029 <- ex1029 %>% 
  filter(Educ >= 8, Exper <= 40, Exper >= 1) %>% 
  filter(Race == 'NotBlack')
########################################################################
```

```{r}
########################################################################
# Load Results #########################################################
load("../../results/ex1029/ex1029_single_minus_log2_ratio2.Rda")
axcon_model <- results$axcon_model
tc_model <- results$tc_model
mod_tc_model <- results$mod_tc_model
log2_sampling_ratio <- results$log2_sampling_ratio
########################################################################
```

```{r}
########################################################################
# Set My Theme for ggplot ##############################################
my_theme <- theme_minimal() +
  theme(
    plot.title = element_text(size = 7),
    axis.title.x = element_text(size = 7),
    axis.text.x = element_text(size = 6),
    axis.title.y = element_text(size = 7),
    axis.text.y = element_text(size = 6),
    legend.title = element_text(size = 7),
    legend.text = element_text(size = 6)
  )
########################################################################
```

```{r}
########################################################################
# Set My Theme for ggplot ##############################################
my_theme_big <- theme_minimal() +
  theme(
    plot.title = element_text(size = 8),
    axis.title.x = element_text(size = 8),
    axis.text.x = element_text(size = 7),
    axis.title.y = element_text(size = 8),
    axis.text.y = element_text(size = 7),
    legend.title = element_text(size = 8),
    legend.text = element_text(size = 7)
  )
########################################################################
```

```{r}
########################################################################
# Draw Partial Plots with Education ####################################
m1 <- 101L
Educ <- seq(min(ex1029$Educ), max(ex1029$Educ), length.out = m1)
Exper <- c(5, 15, 25, 35)

X_plot <- expand.grid(
  list(Educ, Exper)
)
colnames(X_plot) <- c("Educ", "Exper")

axcon_fit_plot <- predict_axcon(axcon_model, X_plot)
#tc_fit_plot <- predict_regmdc(tc_model, X_plot)
#mod_tc_fit_plot <- predict_regmdc(mod_tc_model, X_plot)
```

```{r}
edu_partial_plot_data_frame <- as.data.frame(cbind(
  X_plot, 
  axcon_fit_plot
  #tc_fit_plot,
  #mod_tc_fit_plot
)) %>% 
  rename(
    axcon = axcon_fit_plot
    #tc = tc_fit_plot,
    #mod_tc = mod_tc_fit_plot
  )  
```

```{r}
axcon_edu_partial_plot <- edu_partial_plot_data_frame %>% 
  ggplot() + 
  geom_line(aes(x = Educ, y = axcon, color = factor(Exper))) +
  labs(
    title = "A",
    x = "Education (yrs)", 
    y = "log(Weekly Earnings) (dollars)", 
    color = "Experience (yrs)"
  ) +
  scale_color_viridis_d() +
  my_theme + 
  theme(legend.position = "bottom")

axcon_edu_partial_plot
########################################################################
```


```{r}
########################################################################
# Draw Partial Plots with Experience ###################################
m2 <- 101L
Exper <- seq(min(ex1029$Exper), max(ex1029$Exper), length.out = m2)
Educ <- c(12, 14, 16, 18)

X_plot <- expand.grid(
  list(Educ, Exper)
)
colnames(X_plot) <- c("Educ", "Exper")

axcon_fit_plot <- predict_axcon(axcon_model, X_plot)
tc_fit_plot <- predict_regmdc(tc_model, X_plot)
mod_tc_fit_plot <- predict_regmdc(mod_tc_model, X_plot)
```

```{r}
exp_partial_plot_data_frame <- as.data.frame(cbind(
  X_plot, 
  axcon_fit_plot,
  tc_fit_plot,
  mod_tc_fit_plot
)) %>% 
  rename(
    axcon = axcon_fit_plot,
    tc = tc_fit_plot,
    mod_tc = mod_tc_fit_plot
  )  
```

```{r}
axcon_exp_partial_plot <- exp_partial_plot_data_frame %>% 
  ggplot() + 
  geom_line(aes(x = Exper, y = axcon, color = factor(Educ))) +
  labs(
    title = "B",
    x = "Experience (yrs)", 
    y = "log(Weekly Earnings) (dollars)", 
    color = "Education (yrs)"
  ) +
  scale_color_viridis_d() +
  my_theme + 
  theme(legend.position = "bottom")

axcon_exp_partial_plot

tc_exp_partial_plot <- exp_partial_plot_data_frame %>% 
  ggplot() + 
  geom_line(aes(x = Exper, y = tc, color = factor(Educ))) +
  labs(
    title = "A",
    x = "Experience (yrs)", 
    y = "log(Weekly Earnings) (dollars)", 
    color = "Education (yrs)"
  ) +
  scale_color_viridis_d() +
  my_theme_big + 
  theme(legend.position = "bottom")

tc_exp_partial_plot

mod_tc_exp_partial_plot <- exp_partial_plot_data_frame %>% 
  ggplot() + 
  geom_line(aes(x = Exper, y = mod_tc, color = factor(Educ))) +
  labs(
    title = "B",
    x = "Experience (yrs)", 
    y = "log(Weekly Earnings) (dollars)", 
    color = "Education (yrs)"
  ) +
  scale_color_viridis_d() +
  my_theme_big + 
  theme(legend.position = "bottom")

mod_tc_exp_partial_plot
########################################################################
```

```{r}
########################################################################
# Combine Partial Plots ################################################
axcon_partial_plots <- ggarrange(
  axcon_edu_partial_plot, axcon_exp_partial_plot,
  nrow = 1, ncol = 2, legend = "bottom"
)

axcon_partial_plots

tc_exp_partial_plots <- ggarrange(
  tc_exp_partial_plot, mod_tc_exp_partial_plot,
  nrow = 1, ncol = 2, legend = "bottom"
)

tc_exp_partial_plots
########################################################################
```

```{r, eval = F}
pdf(
  "../../plots/ex1029/axcon_partial_plots.pdf",
  width = 5.9, height = 3.4
)
axcon_partial_plots
dev.off()
```

```{r, eval = F}
pdf(
  "../../plots/ex1029/tc_exp_partial_plots.pdf",
  width = 6.5, height = 3.7
)
tc_exp_partial_plots
dev.off()
```
